Unhandled exception occurred:
Traceback (most recent call last):
  File "main.py", line 111, in <module>
  File "main.py", line 104, in main
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'Mem:'
